### ISSUE TITLE
No module named 'hermeslite2.hermeslite2_swig'

### ISSUE THREAD

**Issue by n7ihq** [daniestevez/gr-hermeslite2#6]
I installed GNU Radio 3.8 and gr-hermeslite2 from the maint-3.8 branch. When I try to run receive.grc from the examples folder I get the following error message:

Traceback (most recent call last):
  File "/home/jim/Documents/GNU Radio/receive.py", line 35, in <module>
    import hermeslite2
  File "/usr/local/lib/python3/dist-packages/hermeslite2/__init__.py", line 27, in <module>
    from .hermeslite2_swig import *
ModuleNotFoundError: No module named 'hermeslite2.hermeslite2_swig'

Can you help me troubleshoot this problem?

**Comment by daniestevez** [comment]
It seems like a problem with swig, so I would suggest to look at the build log and watch out for errors or warnings related to swig. In any case, I would advise to move from GNU Radio 3.8 to 3.10, since 3.8 is end-of-life.

**Comment by n7ihq** [comment]
Thank you for the quick reply! I am developing Hermes Lite 2 support for the [PLSDR](https://github.com/lutusp/PLSDR) application which requires GNU Radio 3.8. I added the following lines to .bashrc:

export PYTHONPATH=/usr/local/lib/python3/dist-packages:$PYTHONPATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

I rebuilt gr-hermeslite2 without errors and ran the example receive.py. Now I get the error message:

Looking for Metis/Hermes card on interface eth0
Interface[0]:lo  Interface[1]:enp0s1  
No eth0 interface.

I can connect to my Hermes Lite 2 using SparkSDR so the ethernet interface is working. Do you have any suggestions? Thanks for your help!

**Comment by daniestevez** [comment]
Looks like you need to set the correct ethernet interface in the Hermes Lite 2 NB block.

**Comment by n7ihq** [comment]
I corrected the receive.grc Ethernet Interface property to "enp0s1" and the receive.grc flowgraph works! This issue is closed.
